spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/fittness
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 3345
